export enum Operations {
	Create = "create",
	Edit = "edit",
  Delete = "delete",
  Approve = "APPROVE",
  Reject = "REJECT",
  Pending = "PENDING",
  Accept = "ACCEPT",
  Received = "RECEIVED",
  Active = "ACTIVE",
  Inactive = "INACTIVE",
  Add = 'add',
  Remove = 'remove',
  Num = "NUM",
  Bool = "BOOL",
}
