#
# © Rolling Array https://rollingarray.co.in/
#
# @summary Deploy C2 DEV app on DEV branch push 
# @author code@rollingarray.co.in
#
# Created at     : 2021-05-26 10:42:18 
# Last modified  : 2021-05-26 10:45:16
#

name: Deploy C2 DEV app on DEV branch push

on: 
  push:
    branches: 
      - dev
      
jobs:
  web-deploy:

    name: Deploy C2 Client Dev
    runs-on: ubuntu-latest

    steps:
    - name: Get latest code
      uses: actions/checkout@v2.3.2

    - name: Use Node.js 14 LTS
      uses: actions/setup-node@v2
      with:
        node-version: '14'
      
    - name: Install NPM Modules
      run: npm install

    - name: Build Project
      run: npm run build --prod
    
    - name: Sync Files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.C2_DEV_UI_SERVER }}
        username: ${{ secrets.C2_DEV_UI_USER }}
        password: ${{ secrets.C2_DEV_UI_PASS }}
        local-dir: ./www/
        server-dir: ${{ secrets.C2_DEV_UI_SERVER_PATH }}
        dangerous-clean-slate: true
